# Generated by Django 4.2.4 on 2024-04-17 17:46

import beverages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
                ('type_icon', models.CharField(default='fa-glass-cheers', max_length=50)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post_link', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to=beverages.models.upload_name)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=1)),
                ('recipe', models.JSONField(blank=True, null=True)),
                ('beverage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beverages.beveragetype')),
            ],
            options={
                'ordering': ['beverage_type', 'order', 'name'],
            },
        ),
    ]
