# Generated by Django 4.2.4 on 2023-08-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0003_alter_beveragetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beveragetype',
            options={'ordering': ['type_name']},
        ),
    ]
