# Generated by Django 4.2.4 on 2023-08-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0004_alter_beveragetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beveragetype',
            options={},
        ),
    ]
