# Generated by Django 4.2.4 on 2023-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0006_alter_beverage_options_alter_beveragetype_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beverage',
            old_name='image_link',
            new_name='post_link',
        ),
        migrations.AddField(
            model_name='beverage',
            name='image',
            field=models.ImageField(blank=True, upload_to='beverages/static/'),
        ),
    ]
