# Generated by Django 4.2.4 on 2023-09-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0009_ingredients_alter_beverage_image_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
